name: 'action-collmex-scraper'
description: 'This action scrape the CSV mapping from Collmex documentation. This mapping is for example used in [`collmex-client`](https://github.com/kaskadi/collmex-client) to parse the response from Collmex API.'
outputs:
  DATA_CHANGED:
    description: 'Tracks if the CSV mapping data has changed. Defined as `Boolean` but you may need to check it against its  `String` version if you are working with conditionals.'
env:
  CMX_USER:
    description: 'Collmex user name to use for authentication. **Recommend storing this in your repository secrets!**'
    required: true
  CMX_PWD:
    description: 'Collmex password to use for authentication. **Recommend storing this in your repository secrets!**'
    required: true
  CMX_CUST_ID:
    description: 'Collmex customer ID. **Recommend storing this in your repository secrets!**'
    required: true
  SATZARTEN_PATH:
    description: 'Relative path from the root of your repository to the file where the data generated by this action will be stored. **If the file already exists:** the action will automatically back it up by appending `.backup` to the file name and duplicating it before updating it.'
    required: true
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
